#####################
# WEI Core Services #
#####################
services:
  x4_wc_server:
    image: ghcr.io/ad-sdl/wei:dev
    container_name: x4_wc_server
    ports:
      - 8000:8000
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
    command: python3 -m wei.server --workcell /workcell_defs/${WORKCELL_FILENAME}
    restart: unless-stopped
    depends_on:
      - x4_wc_redis
  x4_wc_engine:
    image: ghcr.io/ad-sdl/wei:dev
    container_name: x4_wc_engine
    volumes:
      - ${WORKCELLS_DIR}:/workcell_defs
      - ${WEI_DATA_DIR}:/home/app/.wei
    environment:
     - USER_ID=1000
     - GROUP_ID=1000
     - PYTHONUNBUFFERED=1 # Fix weird bug with empty logging
    command: python3 -m wei.engine --workcell /workcell_defs/${WORKCELL_FILENAME}
    restart: unless-stopped
    depends_on:
      - x4_wc_redis
      - x4_wc_server
  x4_wc_redis:
    image: redis
    container_name: x4_wc_redis
    ports:
      - 6379:6379
    volumes:
      - ${REDIS_DIR}:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
